export const recipe_list = [
  {
    id: "1",
    title: "Chocolate Protein Oats",
    img_url: "https://i.ibb.co/FBP3QZ8/breakfast3.jpg",
    subtitle: "Energy Booster",
    desc: "Dive into the creamy delight of Chocolate Protein Overnight Oats. Whole grain oats merge with rich chocolate and a protein boost, creating a decadent yet nutritious start to your day. Sweetened naturally and finished with a hint of sea salt, it's a quick, satisfying fix for your morning cravings.",
    mealType: "Breakfast",
    recipe: {
      title: "Chocolate Protein Oats",
      ingredients: [
        "1/2 cup rolled oats",
        "1 cup almond milk",
        "1 scoop chocolate protein powder",
        "1 tablespoon chia seeds",
        "1 tablespoon cocoa powder",
        "1 tablespoon maple syrup",
        "Pinch of sea salt",
      ],
      instructions: [
        "In a jar or container, mix together rolled oats, almond milk, chia seeds, cocoa powder, maple syrup, and a pinch of sea salt.",
        "Cover and refrigerate overnight, or for at least 4 hours.",
        "In the morning, give the oats a good stir. If desired, add more almond milk for a thinner consistency.",
        "Top with your favorite toppings such as sliced bananas, berries, or nuts.",
        "Enjoy!",
      ],
    },
  },
  {
    id: "2",
    title: "Acai Bowl",
    img_url: "https://i.ibb.co/jWRTjgS/breakfast2.jpg",
    subtitle: "Bliss in a Bowl",
    desc: "Dive into a refreshing Berry Acai Bowl, where the exotic acai berry meets a colorful array of fresh berries. Topped with crunchy granola and a drizzle of honey, this bowl is a perfect harmony of tart, sweet, and crunchy, making it an irresistible, energizing treat.",
    mealType: "Breakfast",
    recipe: {
      title: "Acai Bowl",
      ingredients: [
        "1 packet frozen acai puree",
        "1/2 cup frozen mixed berries",
        "1/2 banana",
        "1/2 cup almond milk",
        "1/4 cup granola",
        "1 tablespoon honey",
        "Toppings of your choice (e.g., sliced bananas, strawberries, blueberries, coconut flakes)",
      ],
      instructions: [
        "In a blender, blend the frozen acai puree, mixed berries, banana, and almond milk until smooth.",
        "Pour the acai mixture into a bowl.",
        "Top with granola, honey, and your choice of toppings.",
        "Serve immediately and enjoy!",
      ],
    },
  },
  {
    id: "3",
    title: "Berry Nut Oatmeal Delight",
    img_url: "https://i.ibb.co/B4vDszf/breakfast1.jpg",
    subtitle: "A Symphony of Wholesome Goodness",
    desc: "Start your day with our Berry Nut Oatmeal Delight, where creamy, slow-cooked oats meet the juicy burst of fresh berries and the earthy crunch of toasted nuts. This heartwarming bowl is a testament to simplicity and nutrition, offering a balanced blend of flavors and textures that nourish the soul and energize the body.",
    mealType: "Breakfast",
    recipe: {
      title: "Berry Nut Oatmeal Delight",
      ingredients: [
        "1/2 cup rolled oats",
        "1 cup water or milk (dairy or non-dairy)",
        "1/2 cup mixed berries (fresh or frozen)",
        "2 tablespoons chopped nuts (e.g., almonds, walnuts)",
        "1 tablespoon honey or maple syrup (optional)",
        "Pinch of cinnamon (optional)",
      ],
      instructions: [
        "In a small saucepan, bring the water or milk to a boil.",
        "Stir in the rolled oats and reduce heat to low.",
        "Simmer, stirring occasionally, for about 5 minutes or until the oats are cooked and creamy.",
        "Remove from heat and stir in the mixed berries, chopped nuts, honey or maple syrup (if using), and cinnamon (if using).",
        "Transfer to a bowl and serve hot.",
        "Enjoy!",
      ],
    },
  },
  {
    id: "4",
    title: "Buddha Bowl",
    img_url: "https://i.ibb.co/1zjdxB0/buddha-Bowl.jpg",
    subtitle: "Delicious and Nutritious",
    desc: "Discover the perfect balance of flavors and nutrients in our Buddha Bowl. Packed with protein, fiber, and essential vitamins.",
    mealType: "Lunch",
    recipe: {
      title: "Buddha Bowl",
      ingredients: [
        "1 cup cooked quinoa or brown rice",
        "1/2 cup cooked chickpeas",
        "1/2 cup roasted sweet potatoes",
        "1/2 cup steamed broccoli",
        "1/4 avocado, sliced",
        "2 tablespoons tahini dressing",
        "Sprinkle of sesame seeds (optional)",
      ],
      instructions: [
        "In a bowl, arrange cooked quinoa or brown rice, cooked chickpeas, roasted sweet potatoes, and steamed broccoli.",
        "Top with sliced avocado and drizzle with tahini dressing.",
        "Sprinkle with sesame seeds if desired.",
        "Serve immediately and enjoy!",
      ],
    },
  },
  {
    id: "5",
    title: "Mediterranean Salad",
    img_url: "https://i.ibb.co/Ps2XDmd/food-Image2.jpg",
    subtitle: "Fresh and Flavorful",
    desc: "Indulge in the vibrant tastes of the Mediterranean with our refreshing salad. Bursting with fresh veggies, olives, feta cheese, and a tangy vinaigrette.",
    mealType: "Lunch",
    recipe: {
      title: "Mediterranean Salad",
      ingredients: [
        "2 cups mixed greens (e.g., lettuce, spinach)",
        "1/2 cup cherry tomatoes, halved",
        "1/4 cup sliced cucumber",
        "2 tablespoons sliced red onion",
        "2 tablespoons sliced Kalamata olives",
        "2 tablespoons crumbled feta cheese",
        "2 tablespoons Greek vinaigrette",
      ],
      instructions: [
        "In a large bowl, combine mixed greens, cherry tomatoes, cucumber, red onion, olives, and feta cheese.",
        "Drizzle with Greek vinaigrette and toss to combine.",
        "Serve immediately and enjoy!",
      ],
    },
  },
  {
    id: "6",
    title: "Veggie Flat Wrap",
    img_url: "https://i.ibb.co/DpqBwpZ/veggie-Wrap.jpg",
    subtitle: "Full of Fiber",
    desc: "Savor the freshness in every bite with our Veggie Wrap, a vibrant medley of crisp vegetables and tangy sauce, all snugly wrapped in a soft, whole-grain tortilla. Perfect for a quick, healthy lunch on the go!",
    mealType: "Lunch",
    recipe: {
      title: "Veggie Flat Wrap",
      ingredients: [
        "1 whole-grain tortilla",
        "1/4 cup hummus",
        "1/2 cup mixed salad greens",
        "1/4 cup sliced cucumber",
        "1/4 cup sliced bell peppers",
        "2 tablespoons shredded carrots",
        "2 tablespoons sliced avocado",
      ],
      instructions: [
        "Spread hummus evenly over the whole-grain tortilla.",
        "Layer mixed salad greens, sliced cucumber, sliced bell peppers, shredded carrots, and sliced avocado on top of the hummus.",
        "Fold the sides of the tortilla and roll tightly to form a wrap.",
        "Slice the wrap in half if desired.",
        "Serve immediately or wrap in foil for later.",
        "Enjoy!",
      ],
    },
  },
  {
    id: "7",
    title: "Pesto Bowtie Pasta",
    img_url: "https://i.ibb.co/s3GLGWz/eaters-collective-12e-HC6-Fx-Pyg-unsplash.jpg",
    subtitle: "A Taste of Italy",
    desc: "Savor the delightful harmony of tender bowtie pasta coated in a luscious basil pesto sauce. Our Pesto Bowtie Pasta offers a burst of fresh flavors with every bite, combining fragrant basil, toasted pine nuts, and grated Parmesan cheese. Perfect for a quick and satisfying meal that brings a taste of Italy to your table.",
    mealType: "Dinner",
    recipe: {
      title: "Pesto Bowtie Pasta",
      ingredients: [
        "8 oz (225g) bowtie pasta",
        "2 cups fresh basil leaves",
        "1/4 cup toasted pine nuts",
        "2 cloves garlic, minced",
        "1/4 cup grated Parmesan cheese",
        "1/3 cup olive oil",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Cook the bowtie pasta according to the package instructions until al dente. Drain and set aside.",
        "In a food processor, combine the fresh basil leaves, toasted pine nuts, minced garlic, grated Parmesan cheese, olive oil, salt, and pepper. Blend until smooth.",
        "In a large bowl, toss the cooked pasta with the pesto sauce until evenly coated.",
        "Serve immediately, garnished with additional grated Parmesan cheese and fresh basil leaves if desired.",
        "Enjoy!",
      ],
    },
  },
  {
    id: "8",
    title: "Golden Butternut Squash Soup",
    img_url: "https://i.ibb.co/xJ9cpb4/monika-grabkowska-VVPC-DEBi2-I-unsplash.jpg",
    subtitle: "A Warm Embrace in a Bowl",
    desc: "Indulge in the comforting warmth of our Golden Butternut Squash Soup, a velvety blend that captures the essence of autumn in every spoonful. Crafted with the finest butternut squash, this soup is gently simmered to perfection, releasing the natural sweetness and rich flavors of the squash. Enhanced with a touch of freshly grated nutmeg and a swirl of cream, it offers a smooth, creamy texture that comforts the soul.",
    mealType: "Dinner",
    recipe: {
      title: "Golden Butternut Squash Soup",
      ingredients: [
        "2 lbs (900g) butternut squash, peeled, seeded, and cubed",
        "1 onion, chopped",
        "2 cloves garlic, minced",
        "4 cups vegetable broth",
        "1/2 teaspoon ground nutmeg",
        "Salt and pepper to taste",
        "1/2 cup heavy cream (optional)",
      ],
      instructions: [
        "In a large pot, heat olive oil over medium heat. Add the chopped onion and minced garlic, and cook until softened.",
        "Add the cubed butternut squash and vegetable broth to the pot. Bring to a boil, then reduce heat to low and simmer until the squash is tender, about 20-25 minutes.",
        "Using an immersion blender, blend the soup until smooth. Alternatively, transfer the soup in batches to a blender and blend until smooth, then return to the pot.",
        "Stir in the ground nutmeg, and season with salt and pepper to taste.",
        "If using, stir in the heavy cream for added richness.",
        "Serve hot, garnished with a drizzle of cream, a sprinkle of ground nutmeg, and fresh parsley if desired.",
        "Enjoy!",
      ],
    },
  },
  {
    id: "9",
    title: "Sunshine Chicken and Yellow Rice",
    img_url: "https://i.ibb.co/SBTX1Wc/likemeat-f96pzs-JZpcs-unsplash.jpg",
    subtitle: "A Vibrant Symphony of Flavors",
    desc: "Savor the harmonious blend of tender chicken and aromatic yellow rice in our delightful Yellow Rice and Chicken dish. Succulent chicken pieces, seasoned to perfection, mingle with fragrant rice infused with turmeric and spices, creating a symphony of flavors that tantalize the taste buds. This classic combination promises a satisfying meal that's both comforting and full of flavor.",
    mealType: "Dinner",
    recipe: {
      title: "Sunshine Chicken and Yellow Rice",
      ingredients: [
        "1 lb (450g) boneless, skinless chicken breasts, cut into bite-sized pieces",
        "1 tablespoon olive oil",
        "1 onion, chopped",
        "2 cloves garlic, minced",
        "1 cup long-grain rice",
        "2 cups chicken broth",
        "1/2 teaspoon ground turmeric",
        "1/2 teaspoon ground cumin",
        "1/4 teaspoon paprika",
        "Salt and pepper to taste",
        "Chopped fresh parsley for garnish",
      ],
      instructions: [
        "In a large skillet, heat olive oil over medium heat. Add the chopped onion and minced garlic, and cook until softened.",
        "Add the chicken pieces to the skillet, and cook until browned on all sides.",
        "Stir in the long-grain rice, chicken broth, ground turmeric, ground cumin, paprika, salt, and pepper.",
        "Bring the mixture to a boil, then reduce heat to low, cover, and simmer for 15-20 minutes or until the rice is cooked and the liquid is absorbed.",
        "Fluff the rice with a fork, and sprinkle with chopped fresh parsley before serving.",
        "Enjoy!",
      ],
    },
  },
];
